
###########################################################################################

[apps.SNI]
cmd = '.\sni.exe'
working_directory='.\sni-v0.0.96-windows-amd64'
args=[]
env = {SNI_USB2SNES_LISTEN_ADDRS='0.0.0.0:23074,0.0.0.0:8080'}
display='SNI'

[apps.FileViewer]
cmd = '.\sni-v0.0.96-windows-amd64\manage_files.exe'
display = 'File Explorer'

[apps.InputViewer]
cmd = '.\sni-v0.0.96-windows-amd64\InputDisplay\snes_input_display-windows-amd64.exe'
display = 'Metroid Inputs'
args=['settings_sm.toml']

[apps.InputViewerSMW]
cmd = '.\sni-v0.0.96-windows-amd64\InputDisplay\snes_input_display-windows-amd64.exe'
display = 'SMW Inputs'
args=['settings_smw.toml']

[apps.Tracker]
cmd = '.\EmoTracker\EmoTracker.exe'

[apps.SMTileViewer]
cmd = '.\sni-v0.0.96-windows-amd64\SMTileViewer\SMTileViewer.exe'
display = 'SM Tile Viewer'

[apps.LiveSplit]
cmd = '.\LiveSplit_1.8.21\LiveSplit.exe'
display = 'Live Split'

###########################################################################################

[webpages]
Funtoon = 'https://funtoon.party/funtoon2snes/'
'Subversion Tracker' = 'https://cout.github.io/sm_subversion_tracker/'

###########################################################################################

[start]
apps = []

###########################################################################################

[snes_controller]
usb2snes_address = 'ws://localhost:23074/'
notes_blurb = '''
    Notes Here...
    '''

###########################################################################################

[expanded_groups]
'SNES Controls' = true
'Custom Apps' = true
Funtoon = false
'Subversion Tracker' = false